server:
  port: 8083

default:
  bake:
    account: default

front50:
  enabled: true
  baseUrl: http://front50-8461235.us-west-2.elb.amazonaws.com:8080
tide:
  baseUrl: http://localhost:8090
oort:
  baseUrl: http://localhost:7002
mort:
  baseUrl: http://localhost:7002
kato:
  baseUrl: http://localhost:7002
echo:
  enabled: false
igor:
  enabled: false
  baseUrl: http://localhost:8088
bakery:
  enabled: false
  baseUrl: http://localhost:8089
  # Rosco exposes more endpoints than Netflix's internal bakery. This disables
  # the use of those endpoints.
  roscoApisEnabled: true
  allowMissingPackageInstallation: false

redis:
  connection: ${REDIS_URL:redis://redis-spinnaker.rnc0rv.0001.usw2.cache.amazonaws.com:6379}

tasks:
  useWaitForAllNetflixAWSInstancesDownTask: false

logging:
  config: classpath:logback-defaults.xml

